services:
  adamastor:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${PWD}/adamastor/:/adamastor"
    environment:
      - ACME_EMAIL=janos.rocha@gmail.com
      - ACME_DOMAIN=jrocha.eu
